/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: amessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "amessage.pb-c.h"
void   amessage__init
                     (AMessage         *message)
{
  static AMessage init_value = AMESSAGE__INIT;
  *message = init_value;
}
size_t amessage__get_packed_size
                     (const AMessage *message)
{
  assert(message->base.descriptor == &amessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t amessage__pack
                     (const AMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &amessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t amessage__pack_to_buffer
                     (const AMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &amessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AMessage *
       amessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AMessage *)
     protobuf_c_message_unpack (&amessage__descriptor,
                                allocator, len, data);
}
void   amessage__free_unpacked
                     (AMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &amessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmessage__init
                     (CMessage         *message)
{
  static CMessage init_value = CMESSAGE__INIT;
  *message = init_value;
}
size_t cmessage__get_packed_size
                     (const CMessage *message)
{
  assert(message->base.descriptor == &cmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmessage__pack
                     (const CMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmessage__pack_to_buffer
                     (const CMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMessage *
       cmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMessage *)
     protobuf_c_message_unpack (&cmessage__descriptor,
                                allocator, len, data);
}
void   cmessage__free_unpacked
                     (CMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor amessage__field_descriptors[3] =
{
  {
    "strr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AMessage, strr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AMessage, t),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "len",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AMessage, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned amessage__field_indices_by_name[] = {
  2,   /* field[2] = len */
  0,   /* field[0] = strr */
  1,   /* field[1] = t */
};
static const ProtobufCIntRange amessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor amessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AMessage",
  "AMessage",
  "AMessage",
  "",
  sizeof(AMessage),
  3,
  amessage__field_descriptors,
  amessage__field_indices_by_name,
  1,  amessage__number_ranges,
  (ProtobufCMessageInit) amessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmessage__field_descriptors[3] =
{
  {
    "strr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMessage, strr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CMessage, t),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "len",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CMessage, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmessage__field_indices_by_name[] = {
  2,   /* field[2] = len */
  0,   /* field[0] = strr */
  1,   /* field[1] = t */
};
static const ProtobufCIntRange cmessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cmessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMessage",
  "CMessage",
  "CMessage",
  "",
  sizeof(CMessage),
  3,
  cmessage__field_descriptors,
  cmessage__field_indices_by_name,
  1,  cmessage__number_ranges,
  (ProtobufCMessageInit) cmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
