/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: amessage.proto */

#ifndef PROTOBUF_C_amessage_2eproto__INCLUDED
#define PROTOBUF_C_amessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _AMessage AMessage;
typedef struct _CMessage CMessage;


/* --- enums --- */


/* --- messages --- */

struct  _AMessage
{
  ProtobufCMessage base;
  char *strr;
  int32_t t;
  int32_t len;
};
#define AMESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&amessage__descriptor) \
    , NULL, 0, 0 }


struct  _CMessage
{
  ProtobufCMessage base;
  char *strr;
  int32_t t;
  int32_t len;
};
#define CMESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmessage__descriptor) \
    , NULL, 0, 0 }


/* AMessage methods */
void   amessage__init
                     (AMessage         *message);
size_t amessage__get_packed_size
                     (const AMessage   *message);
size_t amessage__pack
                     (const AMessage   *message,
                      uint8_t             *out);
size_t amessage__pack_to_buffer
                     (const AMessage   *message,
                      ProtobufCBuffer     *buffer);
AMessage *
       amessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   amessage__free_unpacked
                     (AMessage *message,
                      ProtobufCAllocator *allocator);
/* CMessage methods */
void   cmessage__init
                     (CMessage         *message);
size_t cmessage__get_packed_size
                     (const CMessage   *message);
size_t cmessage__pack
                     (const CMessage   *message,
                      uint8_t             *out);
size_t cmessage__pack_to_buffer
                     (const CMessage   *message,
                      ProtobufCBuffer     *buffer);
CMessage *
       cmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmessage__free_unpacked
                     (CMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*AMessage_Closure)
                 (const AMessage *message,
                  void *closure_data);
typedef void (*CMessage_Closure)
                 (const CMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor amessage__descriptor;
extern const ProtobufCMessageDescriptor cmessage__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_amessage_2eproto__INCLUDED */
